
language: csharp
sudo: false # faster builds
solution: ./ReCaptchaValidator.sln
dist: trusty
notifications:
  email: false
install:
  - dotnet restore ./ReCaptchaValidator.sln
mono: none
dotnet: 2.1.300
script:
  - dotnet restore ./ReCaptchaValidator.sln
  - cd UnitTests/
  - dotnet test
  