
language: csharp
sudo: false # faster builds
solution: ./ReCaptchaValidator.sln
dist: xenial
notifications:
  email: false
install:
  - dotnet restore ./ReCaptchaValidator.sln
mono: none
dotnet: 2.2
script:
  - dotnet restore ./ReCaptchaValidator.sln
  - cd ReCaptchaValidator.Tests/
  - dotnet test
  
