version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Run xunit tests
          command: dotnet test UnitTests/UnitTests.csproj